---
title: "quick_start_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{quick_start_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Seurat)
library(ensemblemerge)
```

```{r}
# example pbmc dataset with 2 batches
pbmc
```

# run individual methods

```{r}
## run uncorrected method
params = setParams(method = "Uncorrected", return = "Seurat") #set params object without integration method and return seurat object
uncorrected = Merge(params, pbmc) # normalizing and scaling data, running pca
uncorrected <- Seurat::RunUMAP(uncorrected, reduction = "pca", dims = 1:20, seed.use = 1) # create umap
uncorrected <- Seurat::FindNeighbors(uncorrected, reduction = 'umap', dims = 1:2, verbose = FALSE) # finding neighbors for clustering umap
uncorrected <- Seurat::FindClusters(uncorrected, algorithm = 3, resolution = 0.01, verbose = FALSE) # finding clusters in umap
uncorrected$cluster <- Seurat::Idents(uncorrected) # assign cluster data to umap

## plotting uncorrected method
Seurat::Idents(uncorrected) = "batch"
p1 <- Seurat::DimPlot(uncorrected, reduction = "umap", pt.size = 0.5, shuffle = TRUE) + ggplot2::ggtitle(label = "Uncorrected Batch")
Seurat::Idents(uncorrected) = "CellType"
p2 <- Seurat::DimPlot(uncorrected, reduction = "umap", pt.size = 0.5, shuffle = TRUE) + ggplot2::ggtitle(label = "Uncorrected Cell Type")
Seurat::Idents(uncorrected) = "cluster"
p3 <- Seurat::DimPlot(uncorrected, reduction = "umap", pt.size = 0.5, shuffle = TRUE) + ggplot2::ggtitle(label = "Uncorrected Cluster")
p1 + p2 + p3
```


```{r}
library(magrittr)
library(Seurat)
# run ensemblemerge
test = EnsembleMerge(pbmc, methods = c("Seurat", "Liger"), return = "Seurat") # running ensemblemerge with Seurat and Harmony methods
```

```{r}
# session
sessionInfo()
```

