#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params SeuratParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "SeuratParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "pca", dims = c(1:20), reduction.name = "Seurat_UMAP", reduction.key = "Seurat_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Seurat_UMAP", dims = 1:2, graph.name = c("Seurat_knn","Seurat_snn"))
  ng <- ng[["Seurat_snn"]]
})

#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params HarmonyParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "HarmonyParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "harmony", dims = c(1:10), reduction.name = "Harmony_UMAP", reduction.key = "Harmony_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Harmony_UMAP", dims = 1:2, graph.name = c("Harmony_knn","Harmony_snn"))
  ng <- ng[["Harmony_snn"]]
})

#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params LigerParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "LigerParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "pca", dims = c(1:10), reduction.name = "Liger_UMAP", reduction.key = "Liger_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Liger_UMAP", dims = 1:2, graph.name = c("Liger_knn","Liger_snn"))
  ng <- ng[["Liger_snn"]]
})

#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params BBKNNParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "BBKNNParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, nn.name = "bbknn", reduction.name = "BBKNN_UMAP", reduction.key = "BBKNN_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "BBKNN_UMAP", dims = 1:2, graph.name = c("BBKNN_knn","BBKNN_snn"))
  ng <- ng[["BBKNN_snn"]]
})

#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params ScanoramaParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "ScanoramaParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "scanorama", dims = c(1:10), reduction.name = "Scanorama_UMAP", reduction.key = "Scanorama_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Scanorama_UMAP", dims = 1:2, graph.name = c("Scanorama_knn","Scanorama_snn"))
  ng <- ng[["Scanorama_snn"]]
})