#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params SeuratParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "SeuratParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "pca", dims = c(1:20), reduction.name = "Seurat_UMAP", reduction.key = "Seurat_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Seurat_UMAP", dims = 1:2, graph.name = c("Seurat_knn","Seurat_snn"))
  ng <- ng[["Seurat_snn"]]
})

#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params HarmonyParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("getNeighborGraph", "HarmonyParams", function(params, data) {
  params@return = "Seurat"
  ng <- Merge(params, data)
  ng <- RunUMAP(ng, reduction = "pca", dims = c(1:10), reduction.name = "Harmony_UMAP", reduction.key = "Harmony_UMAP_")
  ng <- FindNeighbors(ng, compute.SNN = TRUE, reduction = "Harmony_UMAP", dims = 1:2, graph.name = c("Harmony_knn","Harmony_snn"))
  ng <- ng[["Harmony_snn"]]
})