#' Get Neighbor graph
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params SeuratParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod(
	"getNeighborGraph", 
	signature(
		params = "BaseMerge", 
		data = 'Seurat'
	),
	function(params, data, ...) {

		if (params@latent){
    	data <- FindNeighbors(
				data, 
				compute.SNN = TRUE, 
				reduction = params@name,
				dims = 1:params@npcs, 
				graph.name = c(params@knn_name, params@snn_name),
			)
		}else{
			data <- RunUMAP(
				data, 
				reduction = params@name, 
				dims = 1:params@npcs,
				reduction.name = params@umap_name, 
				reduction.key = params@umap_key
			)
    	data <- FindNeighbors(
				data, 
				compute.SNN = TRUE, 
				reduction = params@umap_name, 
				dims = 1:params@umap_dim, 
				graph.name = c(params@knn_name, params@snn_name)
			)	
		}
		data
	}
)
