#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params SeuratParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "SeuratParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Seurat(params, data)

    return(integrated)
})



#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params HarmonyParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "HarmonyParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Harmony(params, data)

    return(integrated)
})



#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params BBKNNParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "BBKNNParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_BBKNN(params, data)

    return(integrated)
})

#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params SMILEParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "SMILEParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_SMILE(params, data)

    return(integrated)
})

#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params ScanoramaParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "ScanoramaParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Scanorama(params, data)

    return(integrated)
})

#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param data SingleCellExperiment object containing single cell counts matrix
#' @param params UncorrectedParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the normalized/scaled data
#' @export
setMethod("Merge", "UncorrectedParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Uncorrected(params, data)

    return(integrated)
})