#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param x SingleCellExperiment object containing single cell counts matrix
#' @param params SeuratParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "SeuratParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Seurat(params, data)

    return(integrated)
})



#' Merge SingleCellExperiment object
#'
#' @import SingleCellExperiment
#' @importFrom methods as
#' @import SummarizedExperiment
#'
#' @param x SingleCellExperiment object containing single cell counts matrix
#' @param params HarmonyParams object generated by setParams()
#' @return returns a SingleCellExperiment object of the integrated data
#' @export
setMethod("Merge", "HarmonyParams", function(params, data) {

    if(class(data) == 'SummarizedExperiment'){
      data = as(data, "SingleCellExperiment") # set data as SingleCellExperiment
    }

    ### checking valid parameters ###
    if(class(data) != 'SingleCellExperiment'){
      stop("Input data must be of SummarizedExperiment or SingleCellExperiment class")
    }

    integrated = run_Harmony(params, data)

    return(integrated)
})